apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-postgres-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-postgres-app
  template:
    metadata:
      labels:
        app: python-postgres-app
    spec:
      containers:
      - name: python-postgres-app
        image: chailearngke/python-postgres-k8s-test:1.0
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres.cvii02ai6sn1.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
